title: Text Summarization Training
version: 1.0.0
description: "Generating the summary of articles given by the user after training a custom model"
long_description: "Text Summarization is the ."

author: "cnvrg"
author_email: "libhub@cnvrg.io"

tags:
  - inference
tasks:
  - title: Train
    top: 400
    left: 300

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: exec

    # The library data
    library: text-summarization-train
    library_version: 1.0.0

    # The flattened library parameters (in this case we have training library)
    command: python3 training_model_summary.py

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: cnvrg:v5.0
    language: python3

    # The "arguments" property changes to "params", rest remains the same.
    # Params in the blueprint yaml can be used to override the arguments in the library.
    params:
      Trained_Model_Name:
        type: 'categorical'
        values:
          - 'My_Custom_Model'
      training_file:
        type: 'categorical'
        values:
          - 'training_data/wiki_lingua_file.csv'
      default_model:
        type: 'categorical'
        values:
          - './Model/Model/'
      train_rows:
        type: 'discrete'
        values:
          - '100'
      encoder_max_length:
        type: 'discrete'
        values:
          - ''
      decoder_max_length:
        type: 'discrete'
        values:
          - ''
      label_smooth_factor:
        type: 'discrete'
        values:
          - ''
      weight_decay_factor:
        type: 'discrete'
        values:
          - ''
  - title: Summarize
    top: 400
    left: 300

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: exec

    # The library data
    library: text-summarization-inference
    library_version: 1.0.0

    # The flattened library parameters (in this case we have training library)
    command: python3 generate_summary.py

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: python:3.8.6
    language: python3

    # The "arguments" property changes to "params", rest remains the same.
    # Params in the blueprint yaml can be used to override the arguments in the library.
    params:
      output_file_name:
        type: 'categorical'
        values:
          - 'summary_generated_1.csv'
      input_path:
        type: 'categorical'
        values:
          - '/input/wikipedia_connector/cnvrg/wiki_output_2.csv'
      default_model:
        type: 'categorical'
        values:
          - '/cnvrg/Model/bart_large_cnn_original_1/'
      min_percent:
        type: 'categorical'
        values::
          - ''
relations:
  - from: Train
    to: Predict