title: Text Summarization Training
version: 1.0.0
description: "Generating the summary of articles given by the user after training a custom model"
long_description: "Text Summarization is the ."

author: "cnvrg"
author_email: "libhub@cnvrg.io"

tags:
  - training
tasks:
  - title: S3 Connector
    top: 300
    left: 0

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: exec

    # The library data
    library: s3-connector
    library_version: 1.0.0

    # The flattened library parameters (in this case we have training library)
    command: python s3-connector.py

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: cnvrg:v5.0
    language: python3

    # The "arguments" property changes to "params", rest remains the same.
    # Params in the blueprint yaml can be used to override the arguments in the library.
    params:
      - key: endpoint
        type: 'categorical'
        values:
          - 'https://s3.amazonaws.com download'
      - key: bucketname
        type: 'categorical'
        values:
          - 'libhub-readme'
      - key: localdir
        type: 'categorical'
        values: '/cnvrg'
      - key: prefix
        type: 'categorical'
        values:
          - 'summerization_data/'
  - title: Train
    top: 400
    left: 300

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: exec

    # The library data
    library: text-summarization-train
    library_version: 1.0.0

    # The flattened library parameters (in this case we have training library)
    command: python3 training_model_summary.py

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: cnvrg:v5.0
    language: python3

    # The "arguments" property changes to "params", rest remains the same.
    # Params in the blueprint yaml can be used to override the arguments in the library.
    params:
      - key: Trained_Model_Name
        type: 'categorical'
        values:
          - 'My_Custom_Model'
      - key: training_file
        type: 'categorical'
        values:
          - '/input/s3_connector/summerization_data/train_data/wiki_lingua_file.csv'
      - key: default_model
        type: 'categorical'
        values:
          - 'bart_large_cnn_original/'
      - key: train_rows
        type: 'discrete'
        values:
          - '100'
      - key: encoder_max_length
        type: 'discrete'
        values:
          - ''
      - key: decoder_max_length
        type: 'discrete'
        values:
          - ''
      - key: label_smooth_factor
        type: 'discrete'
        values:
          - ''
      - key: weight_decay_factor
        type: 'discrete'
        values:
          - ''
  - title: Inference
    top: 400
    left: 500

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: deploy

    # The library data
    library: summarization-inference
    library_version: 1.0.0

    # The flattened library parameters (in this case we have inference library)
    kind: webservice

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: python:3.8.6
    language: python3
    accept_files: false

    file_name: predict.py # the entrypoint file name
    function_name: predict # the entrypoint function
    prep_file: '' # preprocess file name
    prep_function: '' # preprocess function
    input_example:
      text: 'For instance, on the planet Earth, man had always assumed that he was more intelligent than dolphins because he had achieved so much—the wheel, New York, wars and so on—whilst all the dolphins had ever done was muck about in the water having a good time. But conversely, the dolphins had always believed that they were far more intelligent than man—for precisely the same reasons.'
    input_schema:
      text: text
    output_schema:
      prediction: text
relations:
  - from: S3 Connector
    to: Train
  - from: Train
    to: Inference